language: csharp
solution: CnpSdkForNet.sln
notifications:
  email:
    - sdksupport@vantiv.com
dotnet: 2.1
install:
  - nuget restore CnpSdkForNet/CnpSdkForNet.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release CnpSdkForNet/CnpSdkForNet.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe  CnpSdkForNetTest/bin/Debug/CnpSdkForNetTest.exe
after_success:
 - bash <(curl -s https://codecov.io/bash)
  
