language: csharp
solution: CnpSdkForNet.sln
notifications:
  email:
    - sdksupport@vantiv.com
dotnet: 2.1
install:
  - nuget restore CnpSdkForNet/CnpSdkForNet.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release CnpSdkForNet/CnpSdkForNet.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe  CnpSdkForNetTest/bin/Debug/CnpSdkForNetTest.exe
after_success:
 - bash <(curl -s https://codecov.io/bash)
  
